Issue 1 user can access drinks or food search
CristoferMar/cook-it-up pull request #2
Opened 2021-06-13 08:33 UTC by CristoferMar

![image](https://user-images.githubusercontent.com/82407007/121800493-2b57f280-cbe7-11eb-9c34-57a1f3f0c594.png)

Refreshing onto a previously viewed page will be implemented with view sapping implementation.

2021-06-13 17:58 UTC, CristoferMar commented
![CookItUp_Feature_1](https://user-images.githubusercontent.com/82407007/121817401-2bcbaa00-cc36-11eb-9daf-d15a1f081b9c.gif)

2021-06-13 21:36 UTC, codingcodymiller requested changes

2021-06-13 21:36 UTC, codingcodymiller commented on js/main.js
> +  gallery.appendChild($recipeThumb);
You should not append the DOM tree directly inside of the function like this. We want our functions to be reusable, and that makes this function only usable to append to this specific element. Instead, you should return the value from the function, and append it where the function is called.

2021-06-13 21:36 UTC, codingcodymiller commented on js/main.js
> +  gallery.append(none);
Same thing here, `return` rather than append directly.

2021-06-15 00:25 UTC, codingcodymiller approved these changes

2021-06-15 00:28 UTC, merged